version: "3.8"

services:
  customer:
    container_name: customer
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TRIP_SERVICE_URL=http://trip:8083/
      - BING_MAP_SERVICE_URL=http://bing-map:8084/
    networks:
      - my_network
    restart: no

  driver:
    container_name: driver
    build:
      context: ./driver
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - VEHICLE_SERVICE_URL=http://vehicle:8082/
      - TRIP_SERVICE_URL=http://trip:8083/
      - BING_MAP_SERVICE_URL=http://bing-map:8084/
    depends_on:
      - vehicle
    networks:
      - my_network
    restart: no

  vehicle:
    container_name: vehicle
    build:
      context: ./vehicle
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - my_network
    restart: no

  trip:
    container_name: trip
    build:
      context: ./trip
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - my_network
    restart: no

  bing-map:
    container_name: bing-map
    build:
      context: ./bing-map
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - bing.map.apiKey=Aj6QhUcXi3KwZdDylmum4xiiypL9l2s2kqsnhP087cfTuvR2mKY7wuTBDgTfcaKq
    networks:
      - my_network
    restart: no

networks:
  my_network: