version: "3.8"

services:
  customer:
    container_name: customer
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring
    restart: no

  driver:
    container_name: driver
    build:
      context: ./driver
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - vehicle
    networks:
      - spring
    restart: no

  vehicle:
    container_name: vehicle
    build:
      context: ./vehicle
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - spring
    restart: no

networks:
  spring:
    driver: bridge