version: "3.8"

services:
  customer:
    container_name: customer
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring
    restart: no

  driver:
    container_name: driver
    build:
      context: ./driver
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - vehicle
    networks:
      - spring
    restart: no

  vehicle:
    container_name: vehicle
    build:
      context: ./vehicle
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - spring
    restart: no

  trip:
    container_name: trip
    build:
      context: ./trip
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - spring
    restart: no

  bing-map:
    container_name: bing-map
    build:
      context: ./bing-map
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - spring
    restart: no

networks:
  spring:
    driver: bridge