version: "3.8"

services:

  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://localhost:8888
    networks:
      - spring
    restart: no

  customer:
    container_name: customer
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://localhost:8888
    depends_on:
      - config-server
    networks:
      - spring
    restart: no

  driver:
    container_name: driver
    build:
      context: ./driver
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://localhost:8888
    depends_on:
      - config-server
      - vehicle
    networks:
      - spring
    restart: no

  vehicle:
    container_name: vehicle
    build:
      context: ./vehicle
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://localhost:8888
    depends_on:
      - config-server
    networks:
      - spring
    restart: no

networks:
  spring:
    driver: bridge